version: '3.8'

services:
  web:
    build: 
      context: Demo-CI-CD-Azure-AKS
    container_name: web
    working_dir: /usr/src/app
    tty: true
    restart: always
    ports: 
      - "8080:8080"
    expose:
      - "8080"
    networks: 
      - app-net

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    ports:
      - "9113:9113"  # Puerto del exporter
    environment:
      - NGINX_SCRAPE_URI=http://web:8080/nginx_status
    depends_on:
      - web
    networks:
      - app-net
  
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: ejemplodb
    ports:
      - "5432:5432"
    networks: 
      - app-net

  postgres_exporter:
    image: wrouesnel/postgres_exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:pass123@db:5432/ejemplodb?sslmode=disable"
    depends_on:
      - db
    ports:
      - "9187:9187"
    networks:
      - app-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    user: root
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:Z
    depends_on:
      - web
      - postgres_exporter
    networks:
      - app-net

      
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    networks:
      - app-net

networks:
  app-net:
    name: app-net
    driver: bridge