global:
  scrape_interval: 15s

scrape_configs:

  - job_name: 'db'
    static_configs:
      - targets: ['postgres_exporter:9187']
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']